//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppHarbor.TransformTester {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AppHarbor.TransformTester.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;configuration xmlns:xdt=&quot;http://schemas.microsoft.com/XML-Document-Transform&quot;&gt;
        ///  &lt;xdt:Import assembly=&quot;AppHarbor.TransformTester&quot; namespace=&quot;AppHarbor.TransformTester.Transforms&quot;/&gt;
        ///  
        ///  &lt;configSections xdt:Transform=&quot;MergeBefore(/configuration/*)&quot; /&gt;
        ///
        ///  &lt;configSections&gt;
        ///    &lt;section name=&quot;mySection&quot; xdt:Transform=&quot;Insert&quot; /&gt;
        ///  &lt;/configSections&gt;
        ///  
        ///  &lt;connectionStrings xdt:Transform=&quot;Merge&quot; /&gt;
        ///
        ///  &lt;connectionStrings&gt;
        ///    &lt;add name=&quot;bar&quot; connectionString=&quot;value&quot; xdt:Transfor [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DefaultTransformation {
            get {
                return ResourceManager.GetString("DefaultTransformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;configuration&gt;
        ///  &lt;connectionStrings&gt;
        ///    &lt;add name=&quot;foo&quot; connectionString=&quot;value&quot;/&gt;
        ///  &lt;/connectionStrings&gt;
        ///  &lt;system.web&gt;
        ///    &lt;customErrors mode=&quot;Off&quot;/&gt;
        ///  &lt;/system.web&gt;
        ///&lt;/configuration&gt;.
        /// </summary>
        internal static string DefaultWebConfig {
            get {
                return ResourceManager.GetString("DefaultWebConfig", resourceCulture);
            }
        }
    }
}
